#!/usr/bin/env node
// Builds the /design-sync inputs for the @falka/web component library:
//   1. a barrel that re-exports the design-system surface (esbuild bundle entry)
//   2. the brand fonts (Plus Jakarta Sans + Geist) copied into apps/web/.ds-fonts
//   3. a Tailwind v4 compile of the "Suar Dermaga" theme + component utilities
//   4. emitted .d.ts for every scoped component (real prop contracts)
//   5. a one-line index.d.ts the converter reads as the types entry
//
// This script is the DURABLE, committed build for the sync inputs. Everything it
// writes under apps/web/ is generated + gitignored. Run from the repo root:
//   node .design-sync/build-inputs.mjs
// It needs the staged converter deps in .ds-sync/node_modules (Tailwind CLI) —
// recreated by the re-sync setup — and the repo's own typescript.

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const repo = process.cwd();
const web = join(repo, 'apps', 'web');
if (!existsSync(web)) {
  console.error('✗ run from the repo root (apps/web not found)');
  process.exit(1);
}

// ── 1. the scoped component surface (keep in sync with config.json componentSrcMap) ──
const UI = [
  'action-tooltip', 'alert-dialog', 'avatar', 'badge', 'button', 'calendar', 'card',
  'dialog', 'dropdown-menu', 'form', 'input', 'label', 'number-input', 'popover',
  'select', 'separator', 'sheet', 'skeleton', 'sonner', 'switch', 'table', 'tabs',
  'textarea', 'tooltip',
];
const COMPOSITES = [
  'brand-mark', 'date-range-picker', 'empty-state', 'error-screen', 'error-state',
  'low-stock-badge', 'number-delta', 'page-header', 'qr-code-dialog', 'qr-image',
  'stat-card', 'status-badge', 'table-pagination',
];
const CHARTS = [
  'bars', 'channel-donut-chart', 'channel-trend-chart', 'revenue-trend-chart',
  'sparkline', 'stock-flow-chart', 'chart-theme',
];
const MODULES = [
  ...UI.map((f) => `./src/components/ui/${f}`),
  ...COMPOSITES.map((f) => `./src/components/${f}`),
  ...CHARTS.map((f) => `./src/components/charts/${f}`),
];

const banner =
  '// AUTO-GENERATED by /design-sync (.design-sync/build-inputs.mjs) — barrel\n' +
  '// re-exporting the Palka design-system surface onto window.Palka. NOT part of\n' +
  '// the app build (gitignored). Safe to delete; regenerated on every sync.\n';
writeFileSync(join(web, '.ds-entry.tsx'), banner + MODULES.map((m) => `export * from "${m}";`).join('\n') + '\n');
console.error(`  barrel: ${MODULES.length} modules → apps/web/.ds-entry.tsx`);

// ── 2. brand fonts (variable-weight woff2) ──
const FONTS = {
  'PlusJakartaSans-latin.woff2':
    'node_modules/@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-wght-normal.woff2',
  'PlusJakartaSans-latin-ext.woff2':
    'node_modules/@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-ext-wght-normal.woff2',
  'Geist.woff2': 'node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2',
  'GeistMono.woff2': 'node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2',
};
mkdirSync(join(web, '.ds-fonts'), { recursive: true });
for (const [dst, src] of Object.entries(FONTS)) {
  if (!existsSync(join(repo, src))) { console.error(`✗ font missing: ${src}`); process.exit(1); }
  cpSync(join(repo, src), join(web, '.ds-fonts', dst));
}
console.error(`  fonts: ${Object.keys(FONTS).length} woff2 → apps/web/.ds-fonts`);

// ── 3. Tailwind v4 compile (theme tokens + only the utilities the components use) ──
// Header: disable auto content-scan, scope @source to the components + previews,
// ship the brand @font-face + the --font-geist-* vars next/font would set at runtime.
const TW_HEAD = `@import 'tailwindcss' source(none);
@import 'tw-animate-css';
@import 'react-day-picker/style.css';
@source './src';
@source '../../.design-sync/previews';

/* --- Brand fonts shipped with the design-sync bundle (Plus Jakarta Sans + Geist) --- */
@font-face {
  font-family: 'Plus Jakarta Sans Variable';
  font-style: normal;
  font-display: swap;
  font-weight: 200 800;
  src: url('./.ds-fonts/PlusJakartaSans-latin.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304,
    U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF,
    U+FFFD;
}
@font-face {
  font-family: 'Plus Jakarta Sans Variable';
  font-style: normal;
  font-display: swap;
  font-weight: 200 800;
  src: url('./.ds-fonts/PlusJakartaSans-latin-ext.woff2') format('woff2');
  unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308,
    U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F,
    U+A720-A7FF;
}
@font-face {
  font-family: 'Geist';
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url('./.ds-fonts/Geist.woff2') format('woff2');
}
@font-face {
  font-family: 'Geist Mono';
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url('./.ds-fonts/GeistMono.woff2') format('woff2');
}
:root {
  --font-geist-sans: 'Geist';
  --font-geist-mono: 'Geist Mono';
}
`;
const globals = readFileSync(join(web, 'src', 'styles', 'globals.css'), 'utf8')
  .split('\n')
  .filter((l) => !/^@import\s/.test(l)) // the three @imports are re-declared in TW_HEAD
  .join('\n');
writeFileSync(join(web, '.ds-tw-input.css'), TW_HEAD + '\n' + globals);
execFileSync(
  process.execPath,
  [join(repo, '.ds-sync', 'node_modules', '@tailwindcss', 'cli', 'dist', 'index.mjs'),
    '-i', '.ds-tw-input.css', '-o', '.ds-compiled.css'],
  { cwd: web, stdio: 'inherit' },
);
console.error('  css: Tailwind v4 → apps/web/.ds-compiled.css');

// ── 3b. classify framework/motion tokens for check_design_system ──
// claude.ai/design's self-check (check_design_system) scans the compiled CSS for
// custom-property DECLARATIONS (`--x: value;`) and warns on any it can't classify.
// It honors an inline `/* @kind … */` ONLY when it sits on such a declaration, right
// after its `;`. A comment on an `@property … {` SELECTOR line — or on a `@property`
// descriptor line (`syntax`/`inherits`/`initial-value`, which are NOT custom-property
// declarations) — is silently ignored. Verified against the live checker over two runs.
// Tailwind v4 declares the motion/timing theme tokens plus ~237 `--tw-*` plumbing
// declarations (in the universal `@supports … { *,::before,… { --tw-…: …; } }` reset
// block AND in utility classes). NONE are color/spacing/radius/shadow/font design
// tokens → mark them all `other`. There is NO converter knob to exclude `--tw-*` (the
// scan is server-side; the converter never emits a token list — only the element
// `replaces` map), and the source `@theme` block carries no such comments, so
// annotating the GENERATED output is the only available fix.
// See .design-sync/NOTES.md ("check_design_system token kinds").
const compiledCssPath = join(web, '.ds-compiled.css');
let compiledCss = readFileSync(compiledCssPath, 'utf8');
const MOTION_TOKENS = [
  'ease-in-out', 'ease-tide', 'animate-spin', 'animate-ping', 'animate-pulse',
  'aspect-video', 'default-transition-duration', 'default-transition-timing-function',
];
let kindCount = 0;
for (const token of MOTION_TOKENS) {
  compiledCss = compiledCss.replace(
    new RegExp(`^(\\s*--${token}:[^;\\n]*;)(?![^\\n]*@kind)`, 'gm'),
    (m) => (kindCount++, `${m} /* @kind other */`),
  );
}
// Every `--tw-*` custom-property DECLARATION — in the universal reset block AND in
// utility-class bodies — is Tailwind plumbing, not a theme token. Annotate each one
// right after its `;`. This is where the scanner actually finds them; the
// `@property --tw-*` REGISTRATIONS are not token-scope and are left untouched.
// (`[^;{}]*` keeps the match inside a single declaration.)
compiledCss = compiledCss.replace(
  /(--tw-[\w-]+:[^;{}]*;)/g,
  (m) => (kindCount++, `${m} /* @kind other */`),
);
writeFileSync(compiledCssPath, compiledCss);
console.error(`  css: annotated ${kindCount} declarations @kind other (checker classification)`);

// ── 4. emit component .d.ts (real prop contracts for the design agent) ──
writeFileSync(join(web, 'tsconfig.ds.json'), JSON.stringify({
  extends: './tsconfig.json',
  compilerOptions: {
    noEmit: false, declaration: true, emitDeclarationOnly: true, declarationMap: false,
    skipLibCheck: true, incremental: false, composite: false, rootDir: '.', outDir: '.ds-types',
  },
  include: ['.ds-entry.tsx'],
  exclude: ['node_modules', '.ds-types', '.next', 'e2e'],
}, null, 2) + '\n');
execFileSync(
  process.execPath,
  [join(repo, 'node_modules', 'typescript', 'bin', 'tsc'), '-p', 'tsconfig.ds.json'],
  { cwd: web, stdio: 'inherit' },
);
// index.d.ts — the converter's TYPES/discovery entry. Named re-exports of ONLY
// the curated card set (config.json componentSrcMap), so discovery yields exactly
// those components and NOT every sub-export (CardHeader, DialogTrigger, …). The
// bundle entry (.ds-entry.tsx) still export *'s everything onto window.Palka, so
// the full component API stays importable for the design agent's generated code.
const cfg = JSON.parse(readFileSync(join(repo, '.design-sync', 'config.json'), 'utf8'));
const byDts = new Map();
for (const [name, src] of Object.entries(cfg.componentSrcMap ?? {})) {
  const dts = './.ds-types/' + src.replace(/\.tsx?$/, '');
  if (!byDts.has(dts)) byDts.set(dts, []);
  byDts.get(dts).push(name);
}
const indexDts = [...byDts].map(([p, names]) => `export { ${names.join(', ')} } from "${p}";`).join('\n') + '\n';
writeFileSync(join(web, 'index.d.ts'), indexDts);
console.error(`  dts: tsc declaration emit → apps/web/.ds-types; index.d.ts curated to ${Object.keys(cfg.componentSrcMap ?? {}).length} components`);

// ── 5. bundle tsconfig: @/* alias + next/* shims ──
// esbuild's tsconfig-paths resolution (bundle + preview compiles) reads paths
// from the file cfg.tsconfig names. We give it a dedicated tsconfig so next/*
// imports (e.g. ErrorScreen's `next/link`) resolve to lightweight shims instead
// of dragging the Next runtime — whose process.env.__NEXT_* reads throw
// "process is not defined" in the design preview environment.
writeFileSync(join(web, 'tsconfig.ds-bundle.json'), JSON.stringify({
  compilerOptions: {
    baseUrl: '.',
    paths: {
      '@/*': ['./src/*'],
      'next/link': ['../../.design-sync/shims/next-link.tsx'],
      'next/image': ['../../.design-sync/shims/next-image.tsx'],
      'next/navigation': ['../../.design-sync/shims/next-navigation.ts'],
    },
  },
}, null, 2) + '\n');
console.error('  bundle tsconfig: apps/web/tsconfig.ds-bundle.json (@/* + next/* shims)');

console.error('✓ design-sync inputs built');
